### ISSUE TITLE
Add answers to challenge questions

### ISSUE THREAD

**Issue by mqwilber** [mqwilber/2016-04-14-ucsb#14]

**Comment by mqwilber** [comment]
@mqwilber will add these for Unix, Git, and R lessons

**Comment by mqwilber** [comment]
Done for Unix and R.  Doesn't seem to make much sense for Git lessons

**Comment by TomCSmith** [comment]
Should there be answers for Unix lessons on 'Loops', 'Shell Scripts', and 'Finding Things'?  I only see answers for Files..., Creating... and Pipes...

**Comment by mqwilber** [comment]
Didn't figure we we'd get to those ones so I didn't make the answers.  Though on second thought, I'll make one for 'Loops' just in case.

**Comment by TomCSmith** [comment]
Got it.

**Comment by seltmann** [comment]
Were do we put the answer files? In the same folder as the lesson? Adding one for the sql lesson.

**Comment by mqwilber** [comment]
Yeah. And then reference it somewhere on the lesson page like

```
[Answers to SQL questions](./SQL-answers.txt)
```

so that the people can just click on the link and get the answers.
