### ISSUE TITLE
Find time for follow-up sessions

### ISSUE THREAD

**Issue by TomCSmith** [mqwilber/2016-04-14-ucsb#17]
Potential conflicts of scientific computees/R users are:

Cherie's modeling/bio-math course:
R   4:00pm - 4:50pm
F   3:00pm - 4:50pm

Bill Rice's biostats:
M W 10:00am - 11:50am
W   1:00pm - 3:00pm
R   4:00pm - 6:00pm

Cherie's undergrad biostats:
M W F   1:00pm - 1:50pm
M   2:00pm - 3:50pm 
T   2:00pm - 3:50pm 
W   2:00pm - 3:50pm 
R   2:00pm - 3:50pm

**Comment by mqwilber** [comment]
I'm teaching lab for Cherie's class M 2- 3:50 and R 2- 3:50. I do not need to attend the Friday lecture.  We could think about Friday afternoon (again).

**Comment by mqwilber** [comment]
Decided on 11-12 on Tuesdays in Noble 2221.  Booked the room. Let's announce it at the workshop

**Comment by TomCSmith** [comment]
It looks like Tuesday mid-day, post eco-coffee is a good time. Katja teaches at 1, so, we could tell folks 1130 - 1250, and reserve 2221 Noble.  Get coffee, do code. Thanks to whoever reserved that room!
